version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: unasam_app
    container_name: unasam_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8084:80"
    networks:
      - unasam_network
    volumes:
      - ./app:/app
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: unasam_db
    restart: always
    environment:
      SA_PASSWORD: "Unasam2021"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - unasam_network
    volumes:
      - unasam_data:/var/opt/mssql
      - ./backup:/var/opt/mssql/backup

networks:
  unasam_network:
    driver: bridge

volumes:
  unasam_data:
    driver: local
